// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uypnrhdbgxksfgqopqzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cG5yaGRiZ3hrc2ZncW9wcXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjU5MjYsImV4cCI6MjA3MTYwMTkyNn0.cjin0dpI3XNIF0xeaSHepQT8R41vCnbEUCkjVHxYHhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});